infos:
    nom: Festival
    auteur: la couleur du Zèbre
    site: https://www.lacouleurduzebre.com
    description: Thème festival
champs:
    main-color:
        label: "Couleur principale (header, footer)"
        type: color
        defaut: "#363553"
    second-color:
        label: "Deuxième couleur (fonds de certains blocs)"
        type: color
        defaut: "#903775"
    third-color:
        label: "Troisième couleur (boutons)"
        type: color
        defaut: "#E8458B"
    fourth-color:
        label: "Quatrième couleur (fonds de certains blocs)"
        type: color
        defaut: "#DDDDDD"